<a href="https://colab.research.google.com/github/akppan/ml_practice/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
# Importing the dataset
dataset = pd.read_csv('/content/Churn_Modelling.csv')

In [0]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [0]:
#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
print(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
print(X[:,2])
#creating dummy variable
# onehotencoder = OneHotEncoder(categorical_features = [1])
onehotencoder = OneHotEncoder()
print(onehotencoder)
X = onehotencoder.fit_transform(X).toarray()
print(X)
#removing first column to fall into dummy variable trap
X = X[:,1:]

[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
OneHotEncoder(categories='auto', drop=None, dtype=<class 'numpy.float64'>,
              handle_unknown='error', sparse=True)
[[1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 ...
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 [1. 0. 1. ... 0. 1. 0.]]


In [0]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [0]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [0]:
#importing keras library and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [0]:
#initialising ANN
classifier = Sequential()

In [0]:
#Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu',input_dim=11))
# we chose no. of nodes in hidden layer i.e. output_dim = average of(no. of input(columns in X_train) + no. of output(1 in case of classification)) i.e. sum/2
# we specified initialization method
# we specified activation function as rectifier function(relu) for hidden layer and sigmoid for output layer
# input_dim to be used only in first hidden layers to tell the no. of inputs

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#Adding second hidden layer
classifier.add(Dense(output_dim=6,init='uniform',activation='relu'))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#Adding output layer
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))
#If we have more than two variables(let say x) in output then output_dim=x and activation function will change (let say softmax).

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [0]:
#Compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])
# 'adam' is a stochastic gradient descent algorithm
# binary_crossentropy is loss function in adam algorithm for two outputs

In [0]:
# Fitting the ANN to training set
classifier.fit(X_train, y_train, batch_size=10, epochs=100)




Epoch 1/100





7500/7500 [==============================] - 2s 246us/step - loss: 0.5012 - acc: 0.7967
Epoch 2/100
7500/7500 [==============================] - 1s 117us/step - loss: 0.4108 - acc: 0.8104
Epoch 3/100
7500/7500 [==============================] - 1s 126us/step - loss: 0.3817 - acc: 0.8367
Epoch 4/100
7500/7500 [==============================] - 1s 128us/step - loss: 0.3612 - acc: 0.8515
Epoch 5/100
7500/7500 [==============================] - 1s 128us/step - loss: 0.3518 - acc: 0.8564
Epoch 6/100
7500/7500 [==============================] - 1s 121us/step - loss: 0.3477 - acc: 0.8596
Epoch 7/100
7500/7500 [==============================] - 1s 130us/step - loss: 0.3458 - acc: 0.8588
Epoch 8/100
7500/7500 [==============================] - 1s 121us/step - loss: 0.3438 - acc: 0.8589
Epoch 9/100
7500/7500 [==============================] - 1s 125us/step - loss: 0.3430 - acc: 0.8601
Epoch 10/100
7500/7500 [==============================] - 1s 113us/step - loss: 0.3421 - acc

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

ValueError: ignored

In [0]:
cm